language: cpp
dist: trusty
sudo: false

addons:
  apt:
    packages:
      - libboost-dev
      - libboost-system-dev
      - libboost-date-time-dev
      - libsqlite3-dev

compiler: clang

script:
  - make -C Chat-Server --environment-overrides

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    on_success: change
    on_failure: always
